const SET_TOKEN = "SET_TOKEN"
const SET_PROFILE = "SET_PROFILE"
const ADD_CHILD = "ADD_CHILD"
const CREATE_ORDER = "CREATE_ORDER"
const CONTACT_THERAPIST = "CONTACT_THERAPIST"
const GET_USER = "GET_USER"
const PREDICTION_CHILD = "PREDICTION_CHILD"

export { SET_TOKEN, SET_PROFILE, ADD_CHILD, CREATE_ORDER, CONTACT_THERAPIST, GET_USER, PREDICTION_CHILD }