const SET_TOKEN = "SET_TOKEN"
const SET_PROFILE = "SET_PROFILE"
const ADD_CHILD = "ADD_CHILD"
const CREATE_ORDER = "CREATE_ORDER"
const CONTACT_THERAPIST = "CONTACT_THERAPIST"
const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS"

export { SET_TOKEN, SET_PROFILE, ADD_CHILD, CREATE_ORDER, CONTACT_THERAPIST, UPDATE_USER_DETAILS }